"""Initial migration.

Revision ID: 15f8011130f5
Revises: 
Create Date: 2024-09-19 23:21:17.220689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f8011130f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('partner_user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('partner_password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('partner_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('partner_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('partner_password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('partner_user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
