"""Add password_hash column

Revision ID: 78c9833b334d
Revises: 15f8011130f5
Create Date: 2024-09-22 19:29:42.884393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9833b334d'
down_revision = '15f8011130f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('partner_password_hash', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('partner_password')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('partner_password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('partner_password_hash')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
